[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
diesel = { version = "2.0.2", features = ["postgres", "nightly-error-messages"] }
anyhow = "1.0.66"
pbkdf2 = "0.10"
rand_core = { version = "0.6", features = ["std"] }

[dependencies.rocket_http]
version = "0.5.0-rc.2"
features = ["serde"]


[dependencies.tokio]
version = "1.6.1"
features = ["fs", "io-std", "io-util", "rt-multi-thread", "sync", "signal", "macros"]
