name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose
      run: docker-compose -p ci build && docker-compose -p ci up database test --abort-on-container-exit # docker-compose up --abort-on-container-exit
