name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  MONGODB_URI: mongodb+srv://user:oWeLEQtWAp6Pn596@users.phxlx2l.mongodb.net/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: travis_wait 3 cargo test --verbose
